model:

  atom_features:
    - type: "element"
      values: ["H", "C", "N", "O", "F", "Cl", "Br", "S", "P"]
    - type: "connectivity"
      values: [1, 2, 3, 4]
    - type: "avg_formal_charge"
      lowest_energy_only: true
      include_all_transfer_pathways: false
    - type: "ring_size"
      values: [0, 3, 4, 5, 6, 7]
    - type: "is_aromatic"

  bond_features:
    - type: "ring_size"
      values: [0, 3, 4, 5, 6, 7]
    - type: "is_aromatic"

  convolution:
    type: "SAGEConv"
    hidden_feats: [ 128,    128,    128     2 ]
    activation:   [ "ReLU", "ReLU", "ReLU", "Identity" ]

  readouts:
    charges:
      pooling: "atom"
      readout:
        hidden_feats: [ 128,    128,    128     2 ]
        activation:   [ "ReLU", "ReLU", "ReLU", "Identity" ]
      postprocess:
        type: "charges"

data:

  training:
    sources: []
    targets:
      - column: "charges-am1bcc"
        metric: "rmse"
        readout: "charges"
    batch_size: ...

  validation:
    sources: []
    targets:
      - column: "charges-am1bcc"
        metric: "rmse"
        readout: "charges"
    batch_size: ...

  test:
    sources: []
    targets:
      - column: "charges-am1bcc"
        metric: "rmse"
        readout: "charges"
    batch_size: ...

optimizer:
  type: "Adam"
  lr: ...
