name: test
channels:
  - dglteam
  - conda-forge

dependencies:

  - python >3.8
  - pip

  - pydantic
  - jinja2
  - openssl
  - rich

  - rdkit

  - click
  - click-option-group

  - pytorch
  - pytorch-lightning

  - dgl >=0.7

  - pyarrow
  - mlflow

  # Optional dependencies

  ### Computing AM1 charges
  - openff-toolkit-base >=0.11.0
  - ambertools

    # Dev / Testing
  - pre-commit
  - isort
  - black >=23.1
  - flake8

  - pytest
  - pytest-cov
  - pytest-mock
  - codecov
  - coverage >6.4
