name: test
channels:
  - dglteam
  - conda-forge

dependencies:

  - python >3.8
  - pip

  - openff-utilities >=0.1.5
  - pydantic

  - rdkit

  - click
  - click-option-group

  - pytorch
  - dgl >=0.7

  - jinja2
  - tqdm
  - rich

    # Optional dependencies

    ## Model training
  - pytorch-lightning
  - pyarrow
    ## Molecule loading and processing.
  - openff-toolkit-base >=0.11.0
  - ambertools

    # Dev / Testing
  - pre-commit
  - isort
  - black
  - flake8

  - pytest
  - pytest-cov
  - pytest-mock
  - codecov
  - coverage >6.4
