name: test
channels:
  - dglteam
  - conda-forge

dependencies:

  - python >3.8
  - pip

    ### Core dependencies.
  - openff-utilities >=0.1.5
  - pydantic

  - click
  - click-option-group

  - rdkit
  - ambertools

  - pytorch
  - dgl >=0.7

  - tqdm
  - rich

    ### Optional dependencies

    # Model training
  - pytorch-lightning

    # Molecule loading and processing.
  - openff-toolkit-base >=0.11.0

    # SQL based molecule storage.
  - sqlalchemy
  - sqlite

    # Distributed molecule processing / labelling.
  - dask
  - distributed
  - dask-jobqueue

    # Dev / Testing
  - pre-commit
  - isort
  - black
  - flake8

  - pytest
  - pytest-cov
  - codecov
  - coverage >6.4
