name: test
channels:
  - dglteam
  - conda-forge

dependencies:

  - python >3.8
  - pip

  - openff-utilities >=0.1.5
  - pydantic
  - jinja2
  - openssl

  - openff-toolkit-base >=0.11.0
  - rdkit

  - click
  - click-option-group

  - pytorch
  - pytorch-lightning
  - dgl >=0.7
  - pyarrow
  - mlflow

  - tqdm
  - rich

  # Optional dependencies

  ### Computing charges
  - ambertools

    # Dev / Testing
  - pre-commit
  - isort
  - black
  - flake8

  - pytest
  - pytest-cov
  - pytest-mock
  - codecov
  - coverage >6.4
