name: "CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.10" ]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Conda Environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: devtools/envs/base.yaml
        extra-specs: |
          python=${{ matrix.python-version }}

    - name: Install Package
      shell: bash -l {0}
      run: |
        pip install -e .

    - name: Conda Environment Information
      shell: bash -l {0}
      run: |
        conda info
        conda list

    - name: Run Tests
      shell: bash -l {0}
      run: |
        pytest -v --cov=nagl --cov-report=xml --cov-report=term --color=yes nagl/tests/

    - name: CodeCov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
